article = """The founding of a colonial college had long been the desire of John Graves Simcoe, the first Lieutenant-Governor of Upper Canada.[6][7] As an Oxford-educated military commander who had fought in the American Revolutionary War, Simcoe believed a college was needed to counter the spread of republicanism from the United States.[7] The Upper Canada Executive Committee recommended in 1798 a college be established in York, the colonial capital.[7]


A painting by Sir Edmund Walker depicts University College as it appeared in 1858.
On March 15, 1827, a royal charter was formally issued by King George IV, proclaiming "from this time one College, with the style and privileges of a University ... for the education of youth in the principles of the Christian Religion, and for their instruction in the various branches of Science and Literature ... to continue for ever, to be called King's College."[8] The granting of the charter was largely the result of intense lobbying by John Strachan, the influential Anglican Bishop of Toronto who took office as the college's first president.[8][9] The original three-storey Greek Revival school building was built on the present site of Queen's Park.[10][11][12]

Under Strachan's stewardship, King's College was a religious institution closely aligned with the Church of England and the British colonial elite, known as the Family Compact.[13] Reformist politicians opposed the clergy's control over colonial institutions and fought to have the college secularized.[14] In 1849, after a lengthy and heated debate, the newly elected responsible government of Upper Canada voted to rename King's College as the University of Toronto and severed the school's ties with the church.[9] Having anticipated this decision, the enraged Strachan had resigned a year earlier to open Trinity College as a private Anglican seminary.[15] University College was created as the nondenominational teaching branch of the University of Toronto. During the American Civil War, the threat of Union blockade on British North America prompted the creation of the University Rifle Corps, which saw battle in resisting the Fenian raids on the Niagara border in 1866.[16]


A Sopwith Camel aircraft rests on the Front Campus lawn in 1918, during World War I.
Established in 1878, the School of Practical Science was precursor to the Faculty of Applied Science and Engineering, which has been nicknamed Skule since its earliest days.[17] While the Faculty of Medicine opened in 1843, medical teaching was conducted by proprietary schools from 1853 until 1887, when the faculty absorbed the Toronto School of Medicine.[18] Meanwhile, the university continued to set examinations and confer medical degrees.[18] The university opened the Faculty of Law in 1887, followed by the Faculty of Dentistry in 1888, when the Royal College of Dental Surgeons became an affiliate.[9] Women were first admitted to the university in 1884.[19]

A devastating fire in 1890 gutted the interior of University College and destroyed thirty-three thousand volumes from the library,[20] but the university restored the building and replenished its library within two years.[20] Over the next two decades, a collegiate system took shape as the university arranged federation with several ecclesiastical colleges, including Strachan's Trinity College in 1904. The university operated the Royal Conservatory of Music from 1896 to 1991 and the Royal Ontario Museum from 1912 to 1968; both still retain close ties with the university as independent institutions.[21][22] The University of Toronto Press was founded in 1901 as Canada's first academic publishing house.[23] The Faculty of Forestry, founded in 1907 with Bernhard Fernow as dean, was Canada's first university faculty devoted to forest science. In 1910, the Faculty of Education opened its laboratory school, the University of Toronto Schools.

The First and Second World Wars curtailed some university activities as undergraduate and graduate men eagerly enlisted.[24][25] Intercollegiate athletic competitions and the Hart House Debates were suspended, although exhibition and interfaculty games were still held.[25] The David Dunlap Observatory in Richmond Hill opened in 1935, followed by the University of Toronto Institute for Aerospace Studies in 1949.[9][26] The university opened satellite campuses in Scarborough in 1964 and in Mississauga in 1967. The university's former affiliated schools at the Ontario Agricultural College and Glendon Hall became fully independent of the University of Toronto and became part of University of Guelph in 1964 and York University in 1965, respectively. Beginning in the 1980s, reductions in government funding prompted more rigorous fundraising efforts.[9] The University of Toronto was the first Canadian university to amass a financial endowment greater than C$1 billion in 2007.[27]"""